name: "SpringBoot"
on: [push]

jobs:
  setup-build:
    name: setup-build
    strategy:
      matrix:
        version : [17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package -DskipTests